FPS: int = 60

TEAMS = ["Red", "Blue"]
TERRAINS = ["grass", "gold"]

N_TILES_X = 30
N_TILES_Y = 20
TILE_SIZE = 40

MENU_WIDTH = 200
MAP_WIDTH = N_TILES_X * TILE_SIZE
MAP_HEIGHT = N_TILES_Y * TILE_SIZE
SCREEN_WIDTH = MAP_WIDTH + MENU_WIDTH
SCREEN_HEIGHT = MAP_HEIGHT

MIN_WINDOW_WIDTH = 400
 
MINER_SPEED: int = 5
